[debug] [2021-02-12T06:57:00.262Z] ----------------------------------------------------------------------
[debug] [2021-02-12T06:57:00.269Z] Command:       /home/sainyi/.nvm/versions/node/v10.18.0/bin/node /home/sainyi/.nvm/versions/node/v10.18.0/bin/firebase deploy
[debug] [2021-02-12T06:57:00.270Z] CLI Version:   9.1.0
[debug] [2021-02-12T06:57:00.270Z] Platform:      linux
[debug] [2021-02-12T06:57:00.271Z] Node Version:  v10.18.0
[debug] [2021-02-12T06:57:00.287Z] Time:          Fri Feb 12 2021 13:27:00 GMT+0630 (Myanmar Time)
[debug] [2021-02-12T06:57:00.287Z] ----------------------------------------------------------------------
[debug] [2021-02-12T06:57:00.287Z] 
[debug] [2021-02-12T06:57:00.311Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2021-02-12T06:57:00.391Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-02-12T06:57:00.391Z] > authorizing via signed-in user
[debug] [2021-02-12T06:57:00.392Z] [iam] checking project web-messenger-sainyi-068390 for permissions ["firebase.projects.get","firebasehosting.sites.update"]
[debug] [2021-02-12T06:57:00.397Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2021-02-12T06:57:00.398Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-02-12T06:59:10.013Z] [iam] error while checking permissions, command may fail: FirebaseError: Authentication Error: Your credentials are no longer valid. Please run firebase login --reauth

For CI servers and headless environments, generate a new token with firebase login:ci
[debug] [2021-02-12T06:59:10.014Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2021-02-12T06:59:10.014Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-02-12T06:59:10.449Z] <<< HTTP RESPONSE 200 {"cache-control":"no-cache, no-store, max-age=0, must-revalidate","expires":"Mon, 01 Jan 1990 00:00:00 GMT","pragma":"no-cache","date":"Fri, 12 Feb 2021 06:59:10 GMT","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-02-12T06:59:10.509Z] >>> HTTP REQUEST GET https://firebase.googleapis.com/v1beta1/projects/web-messenger-sainyi-068390  
 
[debug] [2021-02-12T06:59:40.542Z] Server Error. ETIMEDOUT
[debug] [2021-02-12T06:59:45.999Z] FirebaseError: Server Error. ETIMEDOUT
    at Request._callback (/home/sainyi/.nvm/versions/node/v10.18.0/lib/node_modules/firebase-tools/lib/api.js:32:31)
    at self.callback (/home/sainyi/.nvm/versions/node/v10.18.0/lib/node_modules/firebase-tools/node_modules/request/request.js:185:22)
    at Request.emit (events.js:198:13)
    at Request.EventEmitter.emit (domain.js:448:20)
    at Timeout.<anonymous> (/home/sainyi/.nvm/versions/node/v10.18.0/lib/node_modules/firebase-tools/node_modules/request/request.js:851:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[error] 
[error] Error: Failed to get Firebase project web-messenger-sainyi-068390. Please make sure the project exists and your account has permission to access it.
